# to true
mongo:
    host: 114.80.150.196
    port: 27777
    user_name: 'fangjia'
    password: 'fangjia123456'
    db: company
    collection: company_test
source_config:
    port: 114.80.150.196
    host: 3336
    user_name: root
    password: fangjia123456
    db_name: company_config

# online
#mongo:
#    host: 114.80.150.196
#    port: 27777
#    user_name: 'fangjia'
#    password: 'fangjia123456'
#    db: company
#    collection: company
