# to true
mongo:
    host: 114.80.150.196
    port: 27777
    user_name: 'fangjia'
    password: 'fangjia123456'
    db: company
    collection: company_test

# online
#mongo:
#    host: 114.80.150.196
#    port: 27777
#    user_name: 'fangjia'
#    password: 'fangjia123456'
#    db: company
#    collection: company
